#!/bin/bash

status=$(playerctl status 2> /dev/null)
if [ $? != 0 ]; then
    echo ""
    exit 0
fi

title=`exec playerctl metadata xesam:title`
artist=`exec playerctl metadata xesam:artist`


if [ "$status" = "Playing" ]; then
    state=""
elif [ "$status" = "Paused" ]; then
    state=""
else
    state=""
fi

echo "$state   $artist: $title"
